services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fitflow-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=FitFlow123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "FitFlow123!" -Q "SELECT 1" -b -o /dev/null
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: fitflow-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

volumes:
  sqlserver_data:
  redis_data: